In [2]:
import pandas
import numpy

In [3]:
jam = pandas.read_csv("/home/songyeji/다운로드/jam.csv")
jam.columns

Index(['code', 'ym', 'gb', 'assets', 'cAssets', 'qAssets', 'inventory',
       'ncAssets', 'iAssets', 'tfAssets', 'ifAssets', 'etcAssets',
       'liabilities', 'cLiabilities', 'ncLiabilities', 'equity', 'netSales',
       'opProfit', 'orProfit', 'netProfit', 'costOfSales', 'grossMargin',
       'smExpense', 'nOpRevenue', 'nOpCost', 'beforeNetProfit', 'tax', 'EPS',
       'dilutedEPS', 'bcash', 'ecash', 'scashflow', 'icashflow', 'fcashflow',
       'salary', 'depreciation', 'amortization', 'IntrstIncome',
       'IntrstExpense', 'GainPPE', 'LossPPE', 'GainIA', 'LossIA', 'GainEquSec',
       'LossEquSec', 'dividend', 'accountReceivable', 'accountPayable',
       'dLiabilities', 'bLiabilities', 'opProfitAnc', 'opProfitCon',
       'opProfitAncCon', 'scashflowCon', 'subInvest', 'earnedSurplus',
       'capitalStock', 'capitalSurplus'],
      dtype='object')

In [4]:
prc = pandas.read_csv("/home/songyeji/다운로드/prc_light_ver.csv", low_memory = False)
prc.columns

Index(['Unnamed: 0', 'stk_cd', 'ymd', 'amt', 'stks', 'cprc1', 'qty1'], dtype='object')

In [5]:
# i년도 j분기(1,4,7,10월)에 대한 데이터

i=2008
j=1
date = i*100+j

data_10 = pandas.read_csv("/home/songyeji/다운로드/시가총액순위/"+str(date)+".csv")
data_10.columns

Index(['순위', '종목코드', '종목명', '시가', '고가', '저가', '현재가', '대비', '등락률(%)', '거래량(주)',
       '거래대금', '시가총액', '시가총액비중(%)', '상장주식수', '외국인보유수량', '외국인 지분율(%)'],
      dtype='object')

In [22]:
from pandas import Series, DataFrame

data=pandas.DataFrame()
stock=pandas.DataFrame()

if j==1:
    myym = date-100+11
else:
    myym = date-1

for name in data_10['종목코드']:
    row = DataFrame(jam[jam['code'].isin([name])])
    row = row[row['ym'].isin([myym])]
    row = row[row['gb'].isin(['1','2','3','4'])]
    row2 = DataFrame(prc[prc['stk_cd'].isin([str(name)])])
    row2 = row2[row2['ymd'].isin(range((myym-2)*100, (myym-2)*100+300))]
    data = data.append(row, ignore_index=True)
    stock = stock.append(row2, ignore_index=True)

In [23]:
stock

     Unnamed: 0 stk_cd       ymd           amt       stks    cprc1        qty1
0       2987744   5930  20071001  196352000000  147299337  11460.0  17162650.0
1       2987745   5930  20071002  349882500000  147299337  11580.0  30136750.0
2       2987746   5930  20071004  455833400000  147299337  11300.0  40348550.0
3       2987747   5930  20071005  329310700000  147299337  11060.0  29788950.0
4       2987748   5930  20071008  309991000000  147299337  11020.0  28390800.0
5       2987749   5930  20071009  437446300000  147299337  10740.0  40724950.0
6       2987750   5930  20071010  356725400000  147299337  11040.0  32597150.0
7       2987751   5930  20071011  332916600000  147299337  11100.0  30210150.0
8       2987752   5930  20071012  633118700000  147299337  11140.0  56563250.0
9       2987753   5930  20071015  370086000000  147299337  10840.0  33940050.0
10      2987754   5930  20071016  697330600000  147299337  10300.0  66853950.0
11      2987755   5930  20071017  369153300000  147299337  10300.0  35884300.0
12      2987756   5930  20071018  313062100000  147299337  10440.0  30044750.0
13      2987757   5930  20071019  520354800000  147299337  10800.0  48519450.0
14      2987758   5930  20071022  345270500000  147299337  10440.0  33010450.0
15      2987759   5930  20071023  335552200000  147299337  10440.0  31971400.0
16      2987760   5930  20071024  418679900000  147299337  10260.0  40471500.0
17      2987761   5930  20071025  377466500000  147299337  10140.0  37307700.0
18      2987762   5930  20071026  537979400000  147299337  10640.0  51448600.0
19      2987763   5930  20071029  437667700000  147299337  10900.0  40179750.0
20      2987764   5930  20071030  208712500000  147299337  10880.0  19168350.0
21      2987765   5930  20071031  304283500000  147299337  11000.0  27734300.0
22      2987766   5930  20071101  294328000000  147299337  10980.0  26799350.0
23      2987767   5930  20071102  258828700000  147299337  10800.0  23918650.0
24      2987768   5930  20071105  292103200000  147299337  10560.0  27602250.0
25      2987769   5930  20071106  334567100000  147299337  10960.0  30758950.0
26      2987770   5930  20071107  672637600000  147299337  11400.0  59272100.0
27      2987771   5930  20071108  483877000000  147299337  10720.0  44275000.0
28      2987772   5930  20071109  346330600000  147299337  10800.0  31995250.0
29      2987773   5930  20071112  274683100000  147299337  10640.0  25916650.0
..          ...    ...       ...           ...        ...      ...         ...
590     8411727  53000  20071115   84811840000  806015340  18400.0   4570025.0
591     8411728  53000  20071116   38257710000  806015340  18500.0   2091766.0
592     8411729  53000  20071119   55633190000  806015340  17950.0   3090543.0
593     8411730  53000  20071120   80176000000  806015340  17300.0   4645905.0
594     8411731  53000  20071121   75438390000  806015340  16500.0   4527241.0
595     8411732  53000  20071122   45465340000  806015340  16700.0   2726276.0
596     8411733  53000  20071123   60536280000  806015340  17050.0   3528870.0
597     8411734  53000  20071126   44616450000  806015340  17250.0   2568705.0
598     8411735  53000  20071127   44172650000  806015340  17200.0   2600408.0
599     8411736  53000  20071128   30839860000  806015340  17150.0   1789196.0
600     8411737  53000  20071129   46105170000  806015340  17250.0   2645791.0
601     8411738  53000  20071130   63865570000  806015340  17700.0   3621838.0
602     8411739  53000  20071203   34118540000  806015340  17250.0   1967081.0
603     8411740  53000  20071204   52145160000  806015340  17450.0   3015368.0
604     8411741  53000  20071205   53266560000  806015340  17150.0   3127756.0
605     8411742  53000  20071206   40083360000  806015340  17450.0   2298232.0
606     8411743  53000  20071207   83352990000  806015340  18000.0   4615260.0
607     8411744  53000  20071210   43043200000  806015340  17850.0   2400387.0
608     8411745  53000  20071211  105844300000  806015340  18300.0   5732147.0
609     8411746  53000  20071212   97270260000  806015340  18050.0   5431565.0
610     8411747  53000  20071213  103722600000  806015340  17700.0   5829432.0
611     8411748  53000  20071214   40439610000  806015340  17600.0   2306318.0
612     8411749  53000  20071217   47367310000  806015340  17450.0   2688774.0
613     8411750  53000  20071218   69659730000  806015340  17850.0   3880878.0
614     8411751  53000  20071220  147005200000  806015340  19050.0   7792585.0
615     8411752  53000  20071221  127721300000  806015340  19550.0   6548943.0
616     8411753  53000  20071224   89025860000  806015340  19850.0   4464550.0
617     8411754  53000  20071226   82646730000  806015340  19300.0   4313891.0
618     8411755  53000  20071227   50962980000  806015340  19000.0   2688643.0
619     8411756  53000  20071228   33523130000  806015340  18850.0   1775308.0

[620 rows x 7 columns]

In [25]:
# 전체 발행 주식 수totStocks, 시가총액capital 월별 평균

totStocks = Series([])
capital = Series([])

for name in data_10['종목코드']:
    row3 = stock[stock['stk_cd'].isin([str(name)])]
    amount_stock = row3['stks'].sum() / len(row3)
    amount_price = row3['cprc1'].sum() / len(row3)
    amount_capital = amount_stock * amount_price
    totStocks = totStocks.append(Series([amount_stock]), ignore_index=True)
    capital = capital.append(Series([amount_capital]), ignore_index=True)
    
capital = capital/1000
name = data_10['종목코드']

prc_result = pandas.DataFrame({
    'name' : name,
    'totstocks' : totStocks,
    'capital' : capital
})

In [26]:
# 분기별 인덱스
# 유동비율cRatio, 부채비율dRatio, 이자보상배율IntrstRatio, 영업이익률OperPercentage, ROA, ROE, BPS, EPS, PBS

result = pandas.DataFrame({
    'name' : name,
   'cRatio' : data['cAssets']/ data['cLiabilities'],
    'dRatio' : data['liabilities']/ data['equity'],
    'IntrstRatio' : data['opProfit']/ data['IntrstExpense'],
    'OperPercentage' : data['opProfit']/ data['netSales'],
    'ROA' : data['netProfit']/ data['assets'],
    'ROE' : data['netProfit']/ data['equity'],
    'BPS' : data['equity']/ totStocks*1000,
    'EPS' : data['netProfit']/ totStocks*1000,
    'PER' : capital/ data['netProfit'],
    'PBR' : capital/ data['equity'],
})

result

,name,cRatio,dRatio,IntrstRatio,OperPercentage,ROA,ROE,BPS,EPS,PER,PBR
0,5930,1.538655,0.264482,155.960115,0.102028,0.033914,0.042815,350753.017985,15017.562503,0.737824,0.031590
1,5490,3.118242,0.244631,31.048186,0.161078,0.023382,0.029121,280823.161295,8177.731477,75.267344,2.191828
2,9540,0.780660,2.069587,200.937872,0.130766,0.030485,0.093664,72049.630974,6748.482750,62.042211,5.811144
3,15760,0.528310,0.490817,-4.970511,-0.121782,-0.009859,-0.014698,68632.524949,-1008.735864,-39.587236,0.581839
4,60000,NaN,12.627147,NaN,0.132117,0.002650,0.036112,47752.295657,1724.435235,41.167288,1.486637
5,55550,NaN,0.408822,2.419426,0.710089,0.008912,0.012556,45538.369560,571.781619,91.976577,1.154862
6,17670,1.647808,0.586445,5.816023,0.106556,0.003640,0.005776,140826.787028,813.467413,290.215246,1.676390
7,34220,2.513685,0.615856,20.899241,0.204173,0.056733,0.091673,23166.599453,2123.741356,22.748199,2.085385
8,66570,0.616311,0.992926,5.732459,0.026186,0.043334,0.086552,49623.148816,4294.990590,21.881425,1.893885
9,53000,NaN,0.163009,3.341475,0.705163,0.007632,0.008877,16206.097269,143.853644,129.892322,1.152991

    name       ROA       BPS       EPS
0   5930  0.033914  2.095506  2.272912
1   5490  0.023382  1.488007  0.879476
2   9540  0.030485 -0.325664  0.588304
3  15760 -0.009859 -0.355349 -0.992026
4  60000  0.002650 -0.536741 -0.435214
5  55550  0.008912 -0.555974 -0.670037
6  17670  0.003640  0.271821 -0.620800
7  34220  0.056733 -0.750324 -0.353866
8  66570  0.043334 -0.520489  0.088469
9  53000  0.007632 -0.810792 -0.757216